name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
    - name: Set up JDK
      uses: actions/setup-java@v4.2.2
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Accept Android SDK licenses
      run: yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.5.0
      with:
        validate-wrappers: true
    - name: Build the app
      run: ./gradlew :app:assembleDebug
